### PR TITLE
Downcase email field

### PR DESCRIPTION
**Pull request by aguspina**
Fix https://github.com/mumuki/mumuki-platform/issues/221

### CODE REVIEW

**Comment by flbulgarelli** [comment]
:warning: You are not actually fixing the core issue, since the emails are still case sensitive, just downcased on save. So if you save `jon.snow@foo.com` and then search by email using uppercase letters - Jon.Snow@foo.com`, the bug still is there. 

Actually it is even worse: if you save 'Jon.snow@foo.com` and then search for it, you won't find it.

**Comment by aguspina** [comment]
But you cannot save an email with capital letters. Because i'm ensuring the
downcase before

**Comment by flbulgarelli** [comment]
> But you cannot save an email with capital letters. Because i'm ensuring the
downcase before

But from the user point of view, you are doing that :P

**Comment by flbulgarelli** [comment]
Close. This PR is outdated

**Pull request closed without merging**
