### PR TITLE
Skipped and passed submissions are solved

### PR DESCRIPTION
**Pull request by felipecalvo**
Requires new mumukit-core at https://github.com/mumuki/mumukit-core/pull/17

### CODE REVIEW

**Comment by felipecalvo** [comment]
I had just force-pushed the gemfile.lock trying to fix the Travis build. No, it didn't fix it :stuck_out_tongue_closed_eyes:

**Comment by felipecalvo** [comment]
I did fix it now.

I don't understand what do you mean with this, though

> Please leave a TODO comment to change it to domain implementation when it is updated in classroom-api

Domain won't be updated in classroom-api, it's not referenced at all.

**Comment by luchotc** [comment]
Nice @felipecalvo.
This branch tries to do so: https://github.com/mumuki/mumuki-classroom-api/pull/153.
I'll add the TODO myself and the merge it :tada:

**Comment by felipecalvo** [comment]
Oops, out of the loop. Forgot about the unification!

**Pull request merged**
